name: gyro
version: '0.2'
summary: Server-less Wiki
description: |
    Gyro aims to produce a delicious, quick wiki that runs with or
    without a server, in a variety of environments.

grade: devel
confinement: devmode

apps:
    gyro:
         command: wrapper
         plugs: [network, x11, unity7, gsettings]

parts:
  gyro:
    plugin: dump
    source: gyro-linux-x64/
    stage-packages: [libgtk2.0-0, libx11-xcb1, libxtst6, libxss1, libgconf-2-4, libnss3, libasound2]
