name: gyro
version: '0.2'
summary: Server-less Wiki
description: |
    Gyro aims to produce a delicious, quick wiki that runs with or
    without a server, in a variety of environments.

grade: devel
confinement: strict

apps:
    gyro:
         command: wrapper
         plugs: [network, unity7, gsettings, browser-support]

parts:
  gyro:
    plugin: dump
    source: gyro-linux-x64/
    stage-packages: [dbus, libdbus-1-3, libgtk2.0-0, libx11-xcb1, libxtst6, libxss1, libgconf-2-4, libnss3, libasound2]
  snapd-xdg-open:
    source: snap/
    plugin: dump
    organize:
      xdg-open: bin/xdg-open
